version: '3'

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379"
    networks:
      - backend

  web:
    image: web
    build:
      context: .
    container_name: token-service
    environment:
      - EXPIRATION=60
    networks:
      - backend
    ports:
      - "3030:3030"
    depends_on:
      - redis

networks:
  backend:
